### ISSUE TITLE
Desynched when watching with someone in a different country

### ISSUE THREAD

**Issue by rickteuthof** [netflixparty1/netflixparty-website#1]
I live in the Netherlands, and I'm trying to watch with someone in the UK. When we watch episode 2 season 4 of The Originals, the person I watch with gets a video file with a recap, while I do not. This obviously causes us to be desynched. I would suggest adding an offset feature, so even if for some reason the video files differ, you can still sync yourself.

**Comment by stepchowfun** [comment]
Hi @rickteuthof, this repository is no longer active, and I no longer own Netflix Party as of 2017. I suggest reaching out to the current Netflix Party owners via the email address listed on the Netflix Party website.
